"""Regenerate THIRD_PARTY_NOTICES.md from cargo metadata.

Lists the Rust crates linked into the extension module (normal dependencies,
no build scripts or proc macros) with their license files. Run from the
repository root: python tools/generate_third_party.py
"""

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OWN = {"pyboy-core", "pyboy-python"}


def cargo(*args):
    return subprocess.run(["cargo", *args], cwd=ROOT, check=True, capture_output=True, text=True).stdout


def main():
    tree = cargo("tree", "-p", "pyboy-python", "--target", "all", "-e", "no-build,no-proc-macro",
                 "--prefix", "none", "-f", "{p}")
    linked = {line.split()[0]: line.split()[1].lstrip("v") for line in tree.splitlines() if line.strip()}
    meta = json.loads(cargo("metadata", "--format-version", "1", "--locked"))
    out = ["# Third-party notices", "",
           "The `pyboy_rs/_native` extension in each wheel statically links the Rust crates below.",
           "PyBoy RS itself is LGPL-3.0-only (see `LICENSE.md`, `COPYING`, `NOTICE`).",
           "Generated by `tools/generate_third_party.py` from `cargo metadata`; do not edit by hand.", ""]
    for package in sorted(meta["packages"], key=lambda p: p["name"]):
        name = package["name"]
        if name in OWN or linked.get(name) != package["version"]:
            continue
        out += [f"## {name} {package['version']}", "",
                f"- License: {package['license']}",
                f"- Source: {package.get('repository') or 'https://crates.io/crates/' + name}", ""]
        directory = Path(package["manifest_path"]).parent
        for path in sorted(directory.iterdir()):
            if path.is_file() and path.name.upper().startswith(("LICENSE", "COPYING", "NOTICE")):
                out += [f"### {path.name}", "", "```text", path.read_text(encoding="utf-8").strip("\n"), "```", ""]
    (ROOT / "THIRD_PARTY_NOTICES.md").write_text("\n".join(out), encoding="utf-8")


if __name__ == "__main__":
    main()
